### ISSUE TITLE
add url fragment to remember user navigation

### ISSUE THREAD

**Issue by emrysr** [TrystanLea/cydynni#18]
maybe use something like https://github.com/davist11/jQuery-One-Page-Nav to allow users to use browser history and to reload the page in the same tab.

![image](https://user-images.githubusercontent.com/1466013/39469406-ecc0c594-4d2f-11e8-8323-e5419301ad9f.png)

**Comment by TrystanLea** [comment]
Diolch https://github.com/TrystanLea/cydynni/pull/33
