### ISSUE TITLE
LCH House test: Schedule not holding

### ISSUE THREAD

**Issue by hiltoni** [TrystanLea/cydynni#3]
The following schedule was set up for SP1:
![c1](https://user-images.githubusercontent.com/33721629/35268799-19e14090-0022-11e8-8720-026cbb8e138f.JPG)
SP1 blue light came on at:

At some point during the schedule running, if I collapse SP1 on the dashboard to look at. e.g., emonTH, SP2 and then go back to open the SP1 view, all input parameters are showing zeros on the dashboard although the schedule continues to run and does not stop at the finish-by time. SP1 remains ON. 
![c2](https://user-images.githubusercontent.com/33721629/35270084-ea059746-0025-11e8-937a-e8e508ebca6d.JPG)
This error is repeatbale on SP1 with the schedule paramters set in the accompanying first diagram.
This does not happen with an identical schedule running for SP2. I can collapse SP2 view as much as I like and the parameters will still be there at the scheduled finish-by time.

**Comment by TrystanLea** [comment]
Thanks Linda, I think I've managed to fix this one now, turns out that on completion of smartplug2 schedule, it was recalculating its schedule but then also overwriting the schedule for smartplug1. I've pushed an ota update

**Comment by hiltoni** [comment]
I will retest on Friday 26/01/18.

**Comment by hiltoni** [comment]
Hi. I can't replicate the error, so I assume that it has been fixed.
Thanks. Happy to Close this one out.
