### ISSUE TITLE
Operational Dashboard: 'exceeding Club consumption' when hydro output is 'very low'

### ISSUE THREAD

**Issue by hiltoni** [TrystanLea/cydynni#39]
Current hydro output at Bethesda is low, however, the dashboard view shows the following message under the forecast graphic as 'exceeding' club consumption:
![180627_issue](https://user-images.githubusercontent.com/33721629/41971162-62434542-7a05-11e8-8743-9fc63df8244c.JPG)

Please can you address ?
Linda

**Comment by TrystanLea** [comment]
This is now fixed :) sorry for the delay
