### ISSUE TITLE
Dashboard scheduler - enhancement

### ISSUE THREAD

**Issue by hiltoni** [TrystanLea/cydynni#6]
It might be useful to have a confirmation of pressing button CLEAR or SAVE (schedule has been cleared / schedule has been saved). It's not obvious whether the button has been pressed properly, thus could cause the user to press again.

**Comment by TrystanLea** [comment]
great, thanks @hiltoni I will look into that

**Comment by emrysr** [comment]
the save and clear buttons now show a message to the user when successful.

**Comment by TrystanLea** [comment]
Diolch!
