### ISSUE TITLE
Dashboard scheduler: Operates with all days greyed out

### ISSUE THREAD

**Issue by hiltoni** [TrystanLea/cydynni#7]
This schedule ran for the half hour:
![c5](https://user-images.githubusercontent.com/33721629/35289097-4bae4c3a-005e-11e8-8e70-11915bdf49b1.JPG)
The next test will be to see if it runs at the same time tomorrow automatically or not, even days are not set :)

**Comment by TrystanLea** [comment]
I think I've fixed this one now, I've added the run once checkbox which clarifies that with all days greyed out the schedule will run the one time and will not repeat every day. Clicking on the run once checkbox also toggles the repeat section 
![runonce](https://user-images.githubusercontent.com/503186/35352591-57f6dbf4-013c-11e8-8444-eba498760d09.png)

**Comment by hiltoni** [comment]
Retest scheduled on Friday 26/01/18

**Comment by hiltoni** [comment]
Tested' Run once' schedule - PASS.
Nice mutually exclusive  feature to prevent me from trying to do both once only and entering a day at the same time. 
Issue can be closed.
