### ISSUE TITLE
Strange device appeared in my list - issue

### ISSUE THREAD

**Issue by hiltoni** [TrystanLea/cydynni#9]
27/01/18 Logged out and logged in at 18:25:

Device 1: appears:
![image](https://user-images.githubusercontent.com/33721629/35475061-a286353e-038f-11e8-822a-bfed4217a55c.png)

opening the view of "device 1:" ;
![image](https://user-images.githubusercontent.com/33721629/35475075-d8f93eea-038f-11e8-9a9b-be9a6a0aea30.png)

Logged out and logged in again.

Device is still in the dashboard device list.

Note also, the devices in my BThome Hub list:
![image](https://user-images.githubusercontent.com/33721629/35475128-dd76d080-0390-11e8-9c18-3a01d6a569d5.png)
Thetwo  SPs are now listed as unknown devices.

It is possible to schedule SPs in this situation and they operate as expected.

**Comment by hiltoni** [comment]
Finally deleted device 1:from the list.

**Comment by TrystanLea** [comment]
Thanks @hiltoni. 

> It is possible to schedule SPs in this situation and they operate as expected.

Yes that should not make any difference. 

Not sure why device 1 is appearing, Il keep an eye out to see if I can replicate the issue.

**Comment by TrystanLea** [comment]
This should now be fixed https://github.com/TrystanLea/cydynni/pull/34
